//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnatisRepository.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractsData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContractsData()
        {
            this.NatisDatas = new HashSet<NatisData>();
        }
    
        public int RecordNumber { get; set; }
        public string ContractNumber { get; set; }
        public string ContractStatus { get; set; }
        public string StatusDescription { get; set; }
        public string VinNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NatisData> NatisDatas { get; set; }
    }
}
