//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnatisRepository.Repo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Intern_LeaveDBEntities : DbContext
    {
        public Intern_LeaveDBEntities()
            : base("name=Intern_LeaveDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ContractNumber> ContractNumbers { get; set; }
        public virtual DbSet<ContractsData> ContractsDatas { get; set; }
        public virtual DbSet<EmployeeData> EmployeeDatas { get; set; }
        public virtual DbSet<NatisData> NatisDatas { get; set; }
        public virtual DbSet<RequestsData> RequestsDatas { get; set; }
        public virtual DbSet<ScanLogsData> ScanLogsDatas { get; set; }
        public virtual DbSet<SentIN_Delivery> SentIN_Delivery { get; set; }
        public virtual DbSet<SentOUT_Delivery> SentOUT_Delivery { get; set; }
        public virtual DbSet<SystemParam> SystemParams { get; set; }
        public virtual DbSet<TickBoxData> TickBoxDatas { get; set; }
    }
}
