//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnatisRepository.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestsData
    {
        public int RecordNumber { get; set; }
        public string RequesterName { get; set; }
        public string RequesterDepartment { get; set; }
        public string RequestStatus { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string Vin { get; set; }
        public string ContractNo { get; set; }
        public Nullable<System.DateTime> ReplyDate { get; set; }
        public string Responder { get; set; }
    }
}
