//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnatisRepository.Repo
{
    using System;
    using System.Collections.Generic;
    
    public partial class SentIN_Delivery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SentIN_Delivery()
        {
            this.ContractNumbers = new HashSet<ContractNumber>();
        }
    
        public int RecordNumber { get; set; }
        public string DealershipName { get; set; }
        public string PackageNumber { get; set; }
        public string PackageSender { get; set; }
        public string PackageRecipient { get; set; }
        public System.DateTime DateSent { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public string CourierStatus { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string DriverDetails { get; set; }
        public string DriverContact { get; set; }
        public string DeliveryChoice { get; set; }
        public string SenderEmail { get; set; }
        public string RecipientEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractNumber> ContractNumbers { get; set; }
    }
}
