//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NatisTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractsData
    {
        public int RecordNumber { get; set; }
        public string ContractNumber { get; set; }
        public string ContractStatus { get; set; }
        public string StatusDescription { get; set; }
        public string VinNumber { get; set; }
    
        public virtual NatisData NatisData { get; set; }
    }
}
