//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NatisTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DriverData()
        {
            this.ContractNumbers = new HashSet<ContractNumber>();
        }
    
        public string SentBy { get; set; }
        public System.DateTime SentDate { get; set; }
        public int ItemQuantity { get; set; }
        public string DriverName { get; set; }
        public string DriverEmail { get; set; }
        public string DriverDepartment { get; set; }
        public string DriverContacts { get; set; }
        public int DriverId { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractNumber> ContractNumbers { get; set; }
    }
}
