//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NatisTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeData
    {
        public int RecordNumber { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string Employee_Surname { get; set; }
        public string ContactName { get; set; }
        public string Password { get; set; }
        public string Department { get; set; }
        public string User_Type { get; set; }
        public string Email { get; set; }
        public string Title { get; set; }
        public string DCXKIM { get; set; }
        public string DCXLDOMAIL { get; set; }
        public string LocationCode { get; set; }
    }
}
