//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NatisTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leave_Days
    {
        public int Emp_ID { get; set; }
        public int Annual_Leave { get; set; }
        public int Sick_Leave { get; set; }
        public int Fam_Leave { get; set; }
        public string App_ID { get; set; }
    }
}
