//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NatisTracker.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Intern_LeaveDBEntities : DbContext
    {
        public Intern_LeaveDBEntities()
            : base("name=Intern_LeaveDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ContractNumber> ContractNumbers { get; set; }
        public virtual DbSet<Leave_Days> Leave_Days { get; set; }
        public virtual DbSet<LogInfo> LogInfoes { get; set; }
        public virtual DbSet<NatisData> NatisDatas { get; set; }
        public virtual DbSet<NatisRequest> NatisRequests { get; set; }
        public virtual DbSet<SentIN_Delivery> SentIN_Delivery { get; set; }
        public virtual DbSet<SentOUT_Delivery> SentOUT_Delivery { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Employee_Table> Employee_Table { get; set; }
    }
}
