//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NatisTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NatisData
    {
        public int RecordNumber { get; set; }
        public string User { get; set; }
        public System.DateTime DateLoaded { get; set; }
        public string ContractNumber { get; set; }
        public string VinNumber { get; set; }
        public string RegistrationNumber { get; set; }
        public string EngineNumber { get; set; }
        public string CarMake { get; set; }
        public string SeriesNumber { get; set; }
        public string Description { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string VehicleStatus { get; set; }
        public string OwnerName { get; set; }
        public string OwnerIdentityNumber { get; set; }
        public string NatisLocation { get; set; }
    }
}
