//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NatisTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NatisDelivery
    {
        public int RecordNumber { get; set; }
        public string DealershipName { get; set; }
        public string PackageNumber { get; set; }
        public string PackageSender { get; set; }
        public string PackageRecipient { get; set; }
        public System.DateTime DateSent { get; set; }
        public Nullable<System.DateTime> DateReceived { get; set; }
        public string CourierStatus { get; set; }
        public string Comment { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string DriverDetails { get; set; }
        public string DriverCantact { get; set; }
        public string DeliveryChoice { get; set; }
    }
}
