//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NatisTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TickBoxData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TickBoxData()
        {
            this.ContractNumbers = new HashSet<ContractNumber>();
        }
    
        public int TableId { get; set; }
        public string SenderName { get; set; }
        public string SenderDepartment { get; set; }
        public System.DateTime SentDate { get; set; }
        public string RecipientName { get; set; }
        public string RecipientDepartment { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public int ItemQuantity { get; set; }
        public string RecipientType { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractNumber> ContractNumbers { get; set; }
    }
}
